const initialState = {
  categories: [
    { id: 'bed', name: 'Bed' },
    { id: 'chair', name: 'Chair' },
    { id: 'sofa', name: 'Sofa' },
    { id: 'table', name: 'Table' },
    { id: 'dining', name: 'Dining' },
  ],
  products: [
    {
      id: 'aenean-ru-bristique-1',
      name: 'Aenean Ru Bristique 1',
      category: 'bed',
      image: 'https://files.tinypic.pl/i/01005/e95n3fkh1qp6.jpeg',
      title: 'cool bed',
      price: 30,
      oldPrice: 25,
      stars: 2,
      promo: 'sale',
      featured: true,
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-2',
      name: 'Aenean Ru Bristique 2',
      image: 'https://files.tinypic.pl/i/01005/lnrrb919kzjz.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      oldPrice: 29,
      stars: 2,
      promo: 'sale',
      featured: true,
      newFurniture: true,
      favorite: 'yes',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-3',
      name: 'Aenean Ru Bristique 3',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      oldPrice: 20,
      stars: 2,
      promo: 'sale',
      featured: true,
      newFurniture: true,
      favorite: '',
      compare: 'yes',
    },
    {
      id: 'aenean-ru-bristique-4',
      name: 'Aenean Ru Bristique 4',
      image: 'https://files.tinypic.pl/i/01005/lwc3nszymldx.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: 'yes',
      compare: 'yes',
    },
    {
      id: 'aenean-ru-bristique-5',
      name: 'Aenean Ru Bristique 5',
      image: 'https://files.tinypic.pl/i/01005/eeifdxl3xn92.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-6',
      name: 'Aenean Ru Bristique 6',
      image: 'https://files.tinypic.pl/i/01005/ijfgm1dyxvmt.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      oldPrice: 23,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-7',
      name: 'Aenean Ru Bristique 7',
      image: 'https://files.tinypic.pl/i/01005/4nyqmfj42t3s.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-8',
      name: 'Aenean Ru Bristique 8',
      image: 'https://files.tinypic.pl/i/01005/2nlvqps4a5gg.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      oldPrice: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-9',
      name: 'Aenean Ru Bristique 9',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-10',
      name: 'Aenean Ru Bristique 10',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      oldPrice: 25,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-11',
      name: 'Aenean Ru Bristique 11',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-12',
      name: 'Aenean Ru Bristique 12',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-13',
      name: 'Aenean Ru Bristique 13',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-14',
      name: 'Aenean Ru Bristique 14',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-15',
      name: 'Aenean Ru Bristique 15',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-16',
      name: 'Aenean Ru Bristique 16',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-17',
      name: 'Aenean Ru Bristique 17',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-18',
      name: 'Aenean Ru Bristique 18',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-19',
      name: 'Aenean Ru Bristique 19',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-20',
      name: 'Aenean Ru Bristique 20',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-21',
      name: 'Aenean Ru Bristique 21',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-22',
      name: 'Aenean Ru Bristique 22',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-23',
      name: 'Aenean Ru Bristique 23',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'aenean-ru-bristique-24',
      name: 'Aenean Ru Bristique 24',
      image: 'https://files.tinypic.pl/i/01005/sw4rl9ag87pr.jpeg',
      title: 'cool bed',
      category: 'bed',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-1',
      name: 'chair-1',
      image:
        'https://i.postimg.cc/d1PcGLfk/all-plastic-chair-dark-grey-1299254-master-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-2',
      name: 'chair-2',
      image: 'https://i.postimg.cc/fTTn748K/alu-group-108-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-3',
      name: 'chair-3',
      image: 'https://i.postimg.cc/xCvD59rs/cassina-K10-dodo-toshiyuki-kita-17-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-4',
      name: 'chair-4',
      image: 'https://i.postimg.cc/gcKb6cHj/denny-008-2-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-5',
      name: 'chair-5',
      image:
        'https://i.postimg.cc/NfJhpNVw/ea-216-215-soft-pad-chair-ea-216-642523-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-6',
      name: 'chair-6',
      image: 'https://i.postimg.cc/g2QCPxmS/gustav-blue-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-7',
      name: 'chair-7',
      image: 'https://i.postimg.cc/kgB0ZQ3R/ipanema-img-0060-988-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-8',
      name: 'chair-8',
      image: 'https://i.postimg.cc/pdjgVPd2/lounge-chair-a-ottoman-xl-49289-1-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-9',
      name: 'chair-9',
      image: 'https://i.postimg.cc/nrn8wNpn/margot-01-2-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-10',
      name: 'chair-10',
      image: 'https://i.postimg.cc/Y9wThT4Q/margot-relax-1-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-11',
      name: 'chair-11',
      image: 'https://i.postimg.cc/LXBwfvfw/organic-chair-73345-2-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-12',
      name: 'chair-12',
      image: 'https://i.postimg.cc/2yTppTSh/eames-plastik-arm-daw-07-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'chair-13',
      name: 'chair-13',
      image: 'https://i.postimg.cc/3N86ZpFR/plywood-group-lcw-f-92099-b.jpg',
      title: 'chair-1',
      category: 'chair',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'sofa-1',
      name: 'sofa-1',
      image: 'https://i.postimg.cc/6qh8ksZc/albert-cutout-03-b.jpg',
      title: 'sofa-1',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'sofa-2',
      name: 'sofa-2',
      image: 'https://i.postimg.cc/763hzvK4/alce-00-b.jpg',
      title: 'sofa-2',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'sofa-3',
      name: 'sofa-3',
      image:
        'https://i.postimg.cc/rwHDXNDB/altair-towarzystwo-projektowe-photo-ernest-winczyk-1-b.jpg',
      title: 'sofa-3',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'sofa-4',
      name: 'sofa-4',
      image: 'https://i.postimg.cc/y8xDbb8h/argo-7-b.jpg',
      title: 'sofa-4',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'sofa-5',
      name: 'sofa-5',
      image: 'https://i.postimg.cc/gcKrkWwq/leya-lounge-couch-009-b.jpg',
      title: 'sofa-5',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'sofa-6',
      name: 'sofa-6',
      image: 'https://i.postimg.cc/SsFjjQ7V/lx675-2-01-b.jpg',
      title: 'sofa-6',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'sofa-7',
      name: 'sofa-7',
      image: 'https://i.postimg.cc/5NnHpVbN/moby-dick-bank-bw-sq-kopie.jpg',
      title: 'sofa-7',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'sofa-8',
      name: 'sofa-8',
      image: 'https://i.postimg.cc/wMFBWXKb/modernista-sofa1-b.jpg',
      title: 'sofa-8',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'sofa-9',
      name: 'sofa-9',
      image: 'https://i.postimg.cc/wBs76RJ7/santiago-sofa-pro-b-arcit18.jpg',
      title: 'sofa-9',
      category: 'sofa',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-1',
      name: 'table-1',
      image: 'https://i.postimg.cc/nL1N90q5/3-stellato-tafeltjes-hires-b.jpg',
      title: 'table-1',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-2',
      name: 'table-2',
      image: 'https://i.postimg.cc/ZYQ2N9yT/billy-wood-70-300-n-b.jpg',
      title: 'table-2',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-3',
      name: 'table-3',
      image:
        'https://i.postimg.cc/hjP6LTrG/embrasse-03-comfortandrelax-coffee-tables-3-b.jpg',
      title: 'table-3',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-4',
      name: 'table-4',
      image: 'https://i.postimg.cc/L5GWF7Mq/icaro-1-2-b.jpg',
      title: 'table-4',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-5',
      name: 'table-5',
      image:
        'https://i.postimg.cc/prmS7v3b/ess-tee-tisch-t-6500-13b-d110-4023-1-pro-b-arcit18.jpg',
      title: 'table-5',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-6',
      name: 'table-6',
      image: 'https://i.postimg.cc/XYfztQ1J/lx639-1-01-b.jpg',
      title: 'table-6',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-7',
      name: 'table-7',
      image:
        'https://i.postimg.cc/G27Nqt7x/screw-cafe-base-with-650-square-natural-oak-top-b.jpg',
      title: 'table-7',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-8',
      name: 'table-8',
      image:
        'https://i.postimg.cc/DybDP2q1/subeybaja-table-furniture-05-robert-heritage-roger-web-santacole-h.jpg',
      title: 'table-8',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-9',
      name: 'table-9',
      image: 'https://i.postimg.cc/rwXHhvJ3/tablotable-602110-1-sq-b.jpg',
      title: 'table-9',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'table-10',
      name: 'table-10',
      image: 'https://i.postimg.cc/8CT0GMxb/trouve-lounge-vrijstaand-3674-b.jpg',
      title: 'table-10',
      category: 'table',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'dining-1',
      name: 'dining-1',
      image: 'https://i.postimg.cc/pTWrKG4n/anna-at-nr1-pro-b-arcit18.jpg',
      title: 'dining-1',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'dining-2',
      name: 'dining-2',
      image: 'https://i.postimg.cc/8kncrbHj/artful-b.jpg',
      title: 'dining-2',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'dining-3',
      name: 'dining-3',
      image: 'https://i.postimg.cc/Zn0qM9Tb/nil-pers-b.jpg',
      title: 'dining-3',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'dining-4',
      name: 'dining-4',
      image: 'https://i.postimg.cc/9fVQjgWN/raba-raba-esstisch-nussbaum-natur-2-b.jpg',
      title: 'dining-4',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'dining-5',
      name: 'dining-5',
      image: 'https://i.postimg.cc/YS3q2N02/ryoba-07-b.jpg',
      title: 'dining-5',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'dining-6',
      name: 'dining-6',
      image: 'https://i.postimg.cc/j5M5c6Y3/stelvio-table-9-1-9-b.jpg',
      title: 'dining-6',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'dining-7',
      name: 'dining-7',
      image: 'https://i.postimg.cc/tJfgQXTh/tc4-3-1-n-b.jpg',
      title: 'dining-7',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'dining-8',
      name: 'dining-8',
      image: 'https://i.postimg.cc/Bn2nkfGK/zio-dining-table-composition-310-2-b.jpg',
      title: 'dining-8',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
    {
      id: 'dining-9',
      name: 'dining-9',
      image: 'https://i.postimg.cc/sDk2TDbz/ninas-ninas-esstisch-eiche-weiss-7-b.jpg',
      title: 'dining-9',
      category: 'dining',
      price: 30,
      stars: 2,
      promo: 'sale',
      newFurniture: true,
      favorite: '',
      compare: '',
    },
  ],
  cart: {
    products: [],
  },
  favorites: ['aenean-ru-bristique-2', 'aenean-ru-bristique-24'],
  ratings: [
    {
      id: 'aenean-ru-bristique-2',
      rate: 3,
    },
  ],
  comparedProducts: {
    products: [],
  },
};

export default initialState;
